### ISSUE TITLE
Infinite "Fetching Symfony services definitions"

### ISSUE THREAD

**Issue by mikbox74** [SplasHmiCH/symfony-vscode#1]
Infinite "Fetching Symfony services definitions", Symfony container view is empty.
OS: Ubuntu 20.04
VS Code: 1.87.2
Project: PHP 8.1, Symfony 5.4 inside container

Config:
```
        "symfony-vscode.enableFileWatching": true,
        "symfony-vscode.shellCommand": "docker exec os-php8.1 /bin/sh -c 'cd ./promonado-new && php \\\"$@\\\"' -- ",
        "symfony-vscode.shellExecutable": "/bin/bash",
        "symfony-vscode.consolePath": "bin/console"
```

Output from Extension Host:

```
2024-03-18 15:29:56.746 [error] [SplasHmiCH.symfony-vscode-fixed] provider FAILED
2024-03-18 15:29:56.749 [error] Error: Illegal argument: character must be non-negative
	at b (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:10:1101)
	at new w (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:148:4602)
	at w.translate (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:148:5225)
	at EditingUtils.getWordRange (/home/<username>/.vscode/extensions/splashmich.symfony-vscode-fixed-0.0.3/out/mvc/editing/EditingUtils.js:10:64)
	at ServiceDocumentationCodeActionProvider.provideCodeActions (/home/<username>/.vscode/extensions/splashmich.symfony-vscode-fixed-0.0.3/out/mvc/editing/codeaction/ServiceDocumentationCodeActionProvider.js:30:69)
	at P.provideCodeActions (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:150:98759)
	at /usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:150:126610
	at Oe.s (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:150:121610)
	at Oe.$provideCodeActions (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:150:126597)
	at s.S (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:147:5519)
	at s.Q (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:147:5285)
	at s.M (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:147:4337)
	at s.L (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:147:3454)
	at w.value (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:147:2241)
	at n.y (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:80:1902)
	at n.fire (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:80:2119)
	at r.fire (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:105:14091)
	at w.value (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:173:8050)
	at n.y (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:80:1902)
	at n.fire (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:80:2119)
	at r.fire (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:105:14091)
	at MessagePortMain.<anonymous> (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:173:6330)
	at MessagePortMain.emit (node:events:514:28)
	at Object.emit (node:electron/js2c/utility_init:2:2285)
```

**Comment by SplasHmiCH** [comment]
This should be fixed in [Version v0.0.4](https://github.com/SplasHmiCH/symfony-vscode/releases/tag/v0.0.4)
